In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
churn=pd.read_csv('diabetes-1.csv')

In [4]:
churn.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
x=churn.iloc[:,0:4].values

In [8]:
y=churn.iloc[:,4].values

In [9]:
x.shape

(768, 4)

In [10]:
y.shape

(768,)

In [11]:
 from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [13]:
x_train.shape

(537, 4)

In [14]:
x_test.shape

(231, 4)

In [15]:
from sklearn.ensemble import RandomForestRegressor
algo_obj=RandomForestRegressor()

In [16]:
algo_obj.fit(x_train,y_train)

RandomForestRegressor()

In [17]:
y_pre=algo_obj.predict(x_train)

In [18]:
y_train

array([  0,   0, 168, 180,  64,  71, 230,   0,   0,   0,   0, 135,  70,
         0, 115,   0,   0,   0, 114,   0, 200, 204,   0,   0,   0, 106,
         0,   0,   0,   0,   0,  82,   0,   0, 304, 310, 100,   0, 105,
         0,   0, 168,  41, 182, 255, 277,   0,   0,   0,   0, 215,   0,
         0,   0,   0,   0,  66, 120, 140, 168, 258,   0, 228,  56,   0,
         0,  54,  83, 545,  54,   0,  66,   0,   0,  54,   0,   0,  58,
       275,  76,   0, 142, 167, 100,   0, 293,  55, 110,  44,   0, 321,
         0,   0,  85,   0,   0,   0,   0,   0,   0,   0, 237,  99, 105,
         0,  43,   0,   0,   0, 190, 132,   0, 188,   0,  88,  14,  36,
       128,  44,  96,   0,   0,   0, 183,   0,   0,  58, 465, 328,   0,
        37,   0,   0,   0, 175,   0,  60,  64, 387,  91,  82,  36,  81,
       145,   0,   0, 130, 600,   0, 225, 140, 130,   0,   0,   0,  88,
         0, 155,   0, 130, 148, 250,   0, 105,   0,   0,   0, 330,  70,
       152, 193,  64, 540,   0,  87,   0,  15,   0,  73,   0,   

In [19]:
y_pre

array([ 22.24,   0.  , 194.98, 133.52,  69.67,  74.78, 210.7 ,   0.  ,
         0.  ,   0.  ,   0.  , 159.59, 126.11,   0.  , 142.9 ,   0.  ,
        19.99,   0.  , 137.39,  48.34, 190.82, 219.76,   0.  ,   0.  ,
         0.  ,  94.44,   0.  ,   0.  ,  13.43,   0.  ,   0.  ,  99.04,
         0.  ,   0.  , 291.47, 256.31,  93.97,  45.57, 119.44,  14.44,
         2.58, 188.61,  46.15, 172.18, 202.13, 246.3 ,   0.  ,   0.  ,
        15.75,   0.  , 178.69,  11.51,  43.45,   0.  ,   0.  ,  20.23,
        60.38, 131.84, 145.56, 163.08, 172.1 ,   0.  , 194.73,  59.9 ,
        54.78,   4.8 ,  65.24,  80.44, 393.56,  48.4 ,  28.87,  64.41,
        91.99,   0.  ,  57.71,  92.39,   0.  ,  78.36, 248.81,  69.13,
        18.87, 123.61, 165.94,  95.77,  16.36, 241.7 ,  48.11, 100.38,
        61.96,   0.  , 241.84,   0.  ,  22.66, 100.73,  12.88,   0.  ,
        33.43,  11.74,  13.44,   0.  ,  81.77, 193.78,  83.81,  97.81,
         0.  ,  44.19,  35.49,   0.  ,  37.14, 146.29, 146.07,   0.  ,
      

In [20]:



from sklearn.metrics import mean_squared_error
import numpy as np
np.sqrt(mean_squared_error(y_train,y_pre))


34.471439680281485

In [21]:
import pickle

In [22]:

pickle.dump(algo_obj,open('algo_obj.txt','wb'))

In [23]:

algo_obj_friend=pickle.load(open('algo_obj.txt','rb'))

In [24]:

algo_obj_friend.predict(x_train)

array([ 22.24,   0.  , 194.98, 133.52,  69.67,  74.78, 210.7 ,   0.  ,
         0.  ,   0.  ,   0.  , 159.59, 126.11,   0.  , 142.9 ,   0.  ,
        19.99,   0.  , 137.39,  48.34, 190.82, 219.76,   0.  ,   0.  ,
         0.  ,  94.44,   0.  ,   0.  ,  13.43,   0.  ,   0.  ,  99.04,
         0.  ,   0.  , 291.47, 256.31,  93.97,  45.57, 119.44,  14.44,
         2.58, 188.61,  46.15, 172.18, 202.13, 246.3 ,   0.  ,   0.  ,
        15.75,   0.  , 178.69,  11.51,  43.45,   0.  ,   0.  ,  20.23,
        60.38, 131.84, 145.56, 163.08, 172.1 ,   0.  , 194.73,  59.9 ,
        54.78,   4.8 ,  65.24,  80.44, 393.56,  48.4 ,  28.87,  64.41,
        91.99,   0.  ,  57.71,  92.39,   0.  ,  78.36, 248.81,  69.13,
        18.87, 123.61, 165.94,  95.77,  16.36, 241.7 ,  48.11, 100.38,
        61.96,   0.  , 241.84,   0.  ,  22.66, 100.73,  12.88,   0.  ,
        33.43,  11.74,  13.44,   0.  ,  81.77, 193.78,  83.81,  97.81,
         0.  ,  44.19,  35.49,   0.  ,  37.14, 146.29, 146.07,   0.  ,
      

In [25]:
y_pred=algo_obj.predict(x_test)

In [26]:
y_test

array([  0,  61, 130, 478, 180,  50,  75,  94,   0,   0,   0,   0,   0,
       100,   0, 165,  50,   0,  42,   0, 160,  76, 115,   0, 105,   0,
       125, 120,  49,   0,   0,   0,   0,  99, 140, 190,   0, 125, 274,
         0,   0,   0,   0,   0,   0,   0, 284, 474,   0,   0, 170,   0,
       105,  59,   0,   0, 220,  86,   0, 119, 165, 325,   0, 680,   0,
       200,   0,   0,   0,   0,   0,   0,   0, 325,  48, 180, 846,  23,
         0, 145, 392,   0,   0,   0,  49,   0, 175,  75,   0,   0, 231,
        57,  53,   0,  60, 230,   0, 220,   0,  77,   0, 215,   0, 166,
        50, 140,   0,   0,   0,   0, 271,  29,   0, 130, 115,  79, 265,
       178,  94,   0,  95, 110,  55, 231,   0, 200,   0,  66, 168, 200,
       194, 485,  76,   0,  49,   0,   0,   0,  52, 144,   0, 144, 130,
        82,   0,  49, 326,   0, 120, 180,   0,   0, 110,  94, 160, 318,
         0,   0,   0,   0, 156,   0,   0,   0, 105,   0, 155,   0,   0,
       182,  48,   0,   0,   0,   0,  63,  94,   0,   0,   0,   

In [27]:

from sklearn.metrics import confusion_matrix

In [28]:

confusion_matrix(y_pred,y_test)

ValueError: Classification metrics can't handle a mix of continuous and multiclass targets