In [ ]:
! pip install scipy

In [ ]:
from scipy import constants

print(constants.liter)

0.001


Scipy is used for performing scientific task.
Modules of Scipy:-
1. Optimization.
2. Linear Algebra.
3. Special Functions.



Features of Scipy;
1. It contains a toolbox and dedicated to common issues in scientific computing.
2. 

In [ ]:
import scipy

print(scipy.__version__)

1.4.1


In [ ]:
#As SciPy is more focused on scientific implementations, it provides many built-in scientific constants.

#These constants can be helpful when you are working with Data Science.

In [ ]:
from scipy import constants

print(constants.pi)
#3.1414------

3.141592653589793


In [ ]:
#Constant Units
#A list of all units under the constants module can be seen using the dir() function.

In [ ]:
from scipy import constants

print(dir(constants))

['Avogadro', 'Boltzmann', 'Btu', 'Btu_IT', 'Btu_th', 'ConstantWarning', 'G', 'Julian_year', 'N_A', 'Planck', 'R', 'Rydberg', 'Stefan_Boltzmann', 'Wien', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_obsolete_constants', 'absolute_import', 'acre', 'alpha', 'angstrom', 'arcmin', 'arcminute', 'arcsec', 'arcsecond', 'astronomical_unit', 'atm', 'atmosphere', 'atomic_mass', 'atto', 'au', 'bar', 'barrel', 'bbl', 'blob', 'c', 'calorie', 'calorie_IT', 'calorie_th', 'carat', 'centi', 'codata', 'constants', 'convert_temperature', 'day', 'deci', 'degree', 'degree_Fahrenheit', 'deka', 'division', 'dyn', 'dyne', 'e', 'eV', 'electron_mass', 'electron_volt', 'elementary_charge', 'epsilon_0', 'erg', 'exa', 'exbi', 'femto', 'fermi', 'find', 'fine_structure', 'fluid_ounce', 'fluid_ounce_US', 'fluid_ounce_imp', 'foot', 'g', 'gallon', 'gallon_US', 'gallon_imp', 'gas_constant', 'gibi', 'giga', 'golden', 'golden_ratio', 'gra

In [ ]:
#Metric (SI) Prefixes:
#Return the specified unit in meter (e.g. centi returns 0.01)

from scipy import constants

print(constants.yotta)    #1e+24
print(constants.zetta)    #1e+21
print(constants.exa)      #1e+18
print(constants.peta)     #1000000000000000.0
print(constants.tera)     #1000000000000.0
print(constants.giga)     #1000000000.0
print(constants.mega)     #1000000.0
print(constants.kilo)     #1000.0
print(constants.hecto)    #100.0
print(constants.deka)     #10.0
print(constants.deci)     #0.1
print(constants.centi)    #0.01
print(constants.milli)    #0.001
print(constants.micro)    #1e-06
print(constants.nano)     #1e-09
print(constants.pico)     #1e-12
print(constants.femto)    #1e-15
print(constants.atto)     #1e-18
print(constants.zepto)  

1e+24
1e+21
1e+18
1000000000000000.0
1000000000000.0
1000000000.0
1000000.0
1000.0
100.0
10.0
0.1
0.01
0.001
1e-06
1e-09
1e-12
1e-15
1e-18
1e-21


In [ ]:
from scipy import constants

print(constants.gram)        #0.001
print(constants.metric_ton)  #1000.0
print(constants.grain)       #6.479891e-05
print(constants.lb)          #0.45359236999999997
print(constants.pound)       #0.45359236999999997
print(constants.oz)          #0.028349523124999998
print(constants.ounce)       #0.028349523124999998
print(constants.stone)       #6.3502931799999995
print(constants.long_ton)    #1016.0469088
print(constants.short_ton)   #907.1847399999999
print(constants.troy_ounce)  #0.031103476799999998
print(constants.troy_pound)  #0.37324172159999996
print(constants.carat)       #0.0002
print(constants.atomic_mass) #1.66053904e-27
print(constants.m_u)         #1.66053904e-27
print(constants.u)

0.001
1000.0
6.479891e-05
0.45359236999999997
0.45359236999999997
0.028349523124999998
0.028349523124999998
6.3502931799999995
1016.0469088
907.1847399999999
0.031103476799999998
0.37324172159999996
0.0002
1.6605390666e-27
1.6605390666e-27
1.6605390666e-27


In [ ]:
# Sub Pakages: A package within a package is called sub package.

#1. scipy.cluster: It deals with the vector quantization or K-means.
##  scipy.fft(): 
#2. scipy.constant(): It represent the physical and mathematical constant.
#3. scipy.integrate(): It defines the integration routines.
#5. scipy.linalg(): it defines the linear Algebra routine.
#6. scipy.io(): Used for data INPUT/OUTPUT.
#7. scipy.signal(): Signal processing.


In [ ]:
#cluster
from numpy import vstack,array
from numpy.random import rand

# data generation with three features
data = vstack((rand(100,3) + array([.5,.5,.5]),rand(100,3)))
data

array([[1.02304537, 1.10308206, 1.33329243],
       [1.39602896, 1.29251818, 1.39776437],
       [1.27468477, 1.49037099, 0.9805089 ],
       [1.43726214, 1.2325313 , 1.49887336],
       [0.72613312, 0.81915702, 0.74850615],
       [1.16086846, 0.995327  , 1.04034   ],
       [1.03955433, 1.10932905, 0.78056465],
       [1.06623766, 1.0566612 , 0.73066817],
       [1.47315982, 1.20105879, 1.18263291],
       [0.98003783, 0.67215872, 0.72414001],
       [1.38922713, 0.94367127, 1.1956393 ],
       [0.87922464, 1.0303029 , 0.72789298],
       [1.04639267, 0.59395454, 1.22230245],
       [1.42104112, 1.13183637, 0.61919021],
       [0.59396075, 1.07311226, 1.29997402],
       [0.56036976, 1.09533063, 0.79731695],
       [1.17059249, 1.24720549, 0.77431914],
       [1.18788764, 1.19139969, 0.67709107],
       [0.53818636, 1.14388088, 0.87162155],
       [0.7049253 , 1.31371799, 1.09958147],
       [1.30365364, 1.16645623, 0.56628342],
       [0.84065539, 0.7679007 , 0.75531664],
       [1.

In [ ]:
import scipy
from scipy.cluster.vq import kmeans,vq,whiten
import numpy as np
# data generation 
data = np.array([[  1.9,2.3,1.7],
                 [  1.5,2.5,2.2],
                 [  0.8,0.6,1.7]])
data


array([[1.9, 2.3, 1.7],
       [1.5, 2.5, 2.2],
       [0.8, 0.6, 1.7]])

In [ ]:
from scipy.cluster.vq import kmeans
centroids = kmeans(data,3)
print(centroids)

(array([[0.8, 0.6, 1.7],
       [1.5, 2.5, 2.2],
       [1.9, 2.3, 1.7]]), 0.0)


In [ ]:
#Fourier Transformation is computed on a time domain signal to check its behavior in the frequency domain. 
#Fourier transformation finds its application in disciplines such as signal and noise processing, image processing, audio signal processing, etc. 
#SciPy offers the fftpack module, which lets the user compute fast Fourier transforms.
#Importing the fft and inverse fft functions from fftpackage
from scipy.fftpack import fft

#create an array with random n numbers
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

#Applying the fft function
y = fft(x)
print(y)

[ 4.5       -0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


# **SciPy Linear Algebra –**
SciPy Linalg
SciPy is one of the fundamental packages for scientific computations. It provides the user with mathematical algorithms and convenient built-in functions. It is handy in the field of data science.

There are modules in SciPy for working with data science, maths, statistics, and also machine learning. We use scipy.linalg modules for working with machine learning concepts. Let us learn more about SciPy Linear Algebra.

SciPy is a very useful scientific library and has very fast computational power. It has functionalities to perform linear algebraic operations. We perform all these operations on the input object and it gives the array as output.

SciPy has all the features included in the NumPy linear algebra module and some extended functionality.

The linalg module has specific functions for different types of operations.

a*x + b*y = c

3x +5y=20

In [ ]:
from scipy import linalg 
import numpy as np
a = np.array([[1,3,2], [4,1,2], [1,5,4]])
b = np.array([4,4,6])
#The solve function
c = linalg.solve(a, b)
print(c)

[ 0.8  1.2 -0.2]


# **Determinant in SciPy**
In linear algebra, we compute the scalar value of the determinant of a square matrix. It is a certain property of the linear transformation of a matrix. The determinant is given by det(A), det A or |A|.

In the linalg module, we have a dedicated function for finding the determinant of a matrix as the linalg.det()function.

The function takes in a matrix input and gives a scalar set of values as output.

In [ ]:
from scipy import linalg
import numpy as np
a = np.array([[5,2,5],[4,1,2],[6,3,6]])
b = np.array([[2,3],[3,2]])
#The determinant function
x = linalg.det(a)
print (x)

5.9999999999999964


# **Eigenvalues and EigenVectors in SciPy**
Eigenvalues and vectors of a matrix of linear equations are a set of non zero vectors that change at ost by a scalar value when we apply the linear transformation. These are also called the characteristic values or roots. The relation between a set of Eigenvalues (λ) and vectors (v) is given by,

Av = λv

scipy.linalg.eig function returns the scalar set of eigenvalues for the matrix.

In [ ]:
from scipy import linalg 
import numpy as np
A = np.array([[5,5],[8,8]])
#Passing the values to the eigen function
val, vect = linalg.eig(A)

#Eigen values
print(val,"\n")
#Eigen vectors
print(vect)

[ 0.+0.j 13.+0.j] 

[[-0.70710678 -0.52999894]
 [ 0.70710678 -0.8479983 ]]


# **Singular Value Decomposition**
Unlike the Eigenvalues and vectors which can compute values only for square matrices, we have the SVD. Standard Value Decomposition is for matrices that are not square in shape.

The scipy.linalg.svd function factorizes the matrix into two unitary matrices and a 1-D array that consists of singular values.

In [ ]:
from scipy import linalg
import numpy as np
a = np.array([[5,5,3],[8,8,3]]) 
#Passing the values to the eigen function
a,b,c = linalg.svd(a)
print(a,b,c)

[[-0.54710208 -0.8370659 ]
 [-0.8370659   0.54710208]] [13.97032406  0.91106849] [[-6.75148088e-01 -6.75148088e-01 -2.97237481e-01]
 [ 2.10178638e-01  2.10178638e-01 -9.54803582e-01]
 [-7.07106781e-01  7.07106781e-01 -6.10622664e-16]]


In [ ]:
from numpy import vstack,array
from numpy.random import rand
# data generation with three features
data = vstack((rand(100,3) + array([.5,.5,.5]),rand(100,3)))


# **Scipy.Stats**

SciPy Stats
The scipy.stats contains a large number of statistics, probability distributions functions. The list of statistics functions can be obtained by info(stats). A list of a random variable can also be acquired from the docstring for the stat sub-package.

Sr.	Function	Description
1.	rv_continuos:	It is a base class to construct specific distribution classes and instances for continuous random variable.
2.	rv_discrete:	It is a base class to construct specific distribution classes and instances for discrete random variables.
3.	rv_histogram:	It can be inherited from rv_continuous class. It generates a distribution given by a histogram.
Normal Continuous Random Variable
There are two general distribution classes which have been implemented for encapsulating continuous random variables and discrete random variable. Here we will discuss about the continuous Random Variables:


In [ ]:
from scipy.stats import norm  
import numpy as np  
print(norm.cdf(np.array([3,-1., 0, 1, 2, 4, -2, 5])))  

[0.9986501  0.15865525 0.5        0.84134475 0.97724987 0.99996833
 0.02275013 0.99999971]




In the above program, first, we need to import the norm module from the scipy.stats, then we passed the data as Numpy array in the cdf() function.

To get the median of the distribution, we can use the Percent Point Function (PPF), this is the inverse of the CDF(Cumulative Distribution Function ).

We can generate the sequence of the random numbers; the size argument is necessary to pass the size parameter.
 

In [ ]:

from scipy.stats import norm  
print(norm.rvs(size = 4)) 


The output can vary when we run the program every time. We can use the seed() function to generate the same random numbers.

Descriptive Statistics
The descriptive statistics describe the values of observation in a variable. There are various stats such as Min, Max, and Variance, that take the Numpy array as input and returns the particular results. Some essential functions provide by scipy.stats package are described in the following image.

Sr.	Function	Description
1.	describe()	Computes various descriptive statistics of the input array.	
2.	gmean()	Computes geometric mean along with the specified.	
3.	hmean()	Calculates the harmonic mean along the specified axis.	
4.	kurtosis()	Computes the Kurtosis.	
5.	mode()	Returns the mode value.	
6.	skew()	Tests the skewness of the data	
7.	zscore()	It calculates the z score of each value in the sample, relative to the sample mean and standard deviation.	
Let us consider the following program:



In [4]:
import scipy as sp  
import numpy as np  
from scipy.stats import norm  
number_of_data = 100  
random_data_set = sp.randn(number_of_data)  
#print(random_data_set)
print(random_data_set.mean())  
print(sp.median(random_data_set))  
min_max = np.array([random_data_set.min(),random_data_set.max()])  
print(min_max)  
sp.stats.describe(random_data_set)  



-0.030694360318650128
0.026290860191181868
[-2.84558093  2.18064595]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: scipy.randn is deprecated and will be removed in SciPy 2.0.0, use numpy.random.randn instead
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  


DescribeResult(nobs=100, minmax=(-2.8455809318711984, 2.180645947975023), mean=-0.030694360318650128, variance=0.9710593535353396, skewness=-0.15675527923699756, kurtosis=-0.19024183574016051)


DescribeResult(nobs=100, minmax=(-2.1865824992721987, 2.475379209985273), mean=0.006283818005153084, variance=1.0933102537156147, skewness=0.027561719919920322, kurtosis=-0.6958272633471831)
T-Test
The t-test is used to compare two averages (means) and tells that if these averages are different from each other. The t-test is also described as significant in the differences between the groups.

T-score
The t-score is a ratio between two groups and the difference within the groups. The smaller the t-score shows that the groups are relatively similar, and the more significant t-score indicates, the more difference between the groups.

Comparing two samples

The two samples are given that can come either from the same or from difference distributions and we want to test whether these samples have the same statistical properties.

from scipy import stats  
rvs = stats.norm.rvs(loc = 6, scale = 10, size = (50,2))  
print(stats.ttest_1samp(rvs,5.0))  
Output:

Ttest_1sampResult(statistic=array([0.42271098, 1.1463823 ]), pvalue=array([0.67435547, 0.25720448]))
In the above output, a p-value is a probability that the results from your sample data occurred by chance. P-values are from 0% to 100%.

SciPy Linear Regression
Linear regression is used to find the relationship between the two variables. The SciPy provides linregress() function to perform linear regression. The syntax is given below:

scipy.stats.linregress(x,y=None)  
Parameters:

x, y: These two parameters should be an array and have the same length.

There are two types of linear regression.

Simple regression
Multivariable regression
Simple Regression

Simple linear regression is a method for predicting a response using a single feature. It is assumed that the two variables are linearly related, which means the other variable can accurately predict one variable. For example, using temperature in the degree Celsius, it is correctly predicted in Fahrenheit.

Multivariable Regression

Multiple linear regression is described as the relationship between one continuous dependent variable and two or more independent variables.

price(dependent variable) = m1*area + m2*bedrooms + m2*age(independent variable)  
The variable price is dependent on the other variables.